#!/usr/bin/env bash

LOGFILE="/home/gitpod/extensions/vsix-installer.log"
WORKER="/home/gitpod/extensions/install-vsix.sh"

# hint once
echo "[Info] VSIX installer log: $LOGFILE"

# fire-and-forget, redirect all output
[[ -x $WORKER ]] && nohup bash "$WORKER" >>"$LOGFILE" 2>&1 &

# always succeed, fast return
: